name: "📚 Blog Updater"

on:
  workflow_dispatch:

jobs:
  update_blogs:
    name: "Update Blogs"
    runs-on: ubuntu-latest
    steps:
      - name: "📥  Fetching Repository Contents"
        uses: actions/checkout@main

      - name: "📚  Hashnode Updater"
        uses: "varunsridharan/action-hashnode-blog@main"
        with:
          USERNAME: "adityadhopade88" # Hashnode Username
          BLOG_URL: "https://codemyworld.hashnode.dev/" # Blog URL
          COUNT: 5 # MAX Visisble
        env:
          GITHUB_TOKEN: ${{ secrets.SECRET_GITHUB_TOKEN }}
